FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --default-timeout=1800 --retries 10 -r /tmp/requirements.txt

COPY frontend ./frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]